SET(DepName "gclvorbis")
IF(${WIN32})
	IF(${IS_MSVC})
		SET(VORBIS_ROOT "${CMAKE_CURRENT_LIST_DIR}")
		SET(LPATH ${VORBIS_ROOT}/lib/${KINEVOX_ARCHITECTURE})
		SET(LIB_NAME "libvorbis_static")
		SET(LIB_NAME2 "libvorbisfile_static")
	ELSEIF(${IS_GNU})
		SET(VORBIS_ROOT "${MSYS_PATH}/local")		
		SET(LPATH ${VORBIS_ROOT}/lib/)
		SET(LIB_NAME "libvorbis")
		SET(LIB_NAME2 "libvorbisfile")
	ENDIF()
	
	SET(VORBIS_INCLUDE_DIR ${VORBIS_ROOT}/include)
	FindLibrary(VORBIS_LIBRARY ${LIB_NAME} ${LPATH})
	FindLibrary(VORBIS_LIBRARY2 ${LIB_NAME2} ${LPATH})
	  
	SET(${DepName}_INCLUDE_DIR ${VORBIS_INCLUDE_DIR} )
	list(APPEND ${DepName}_LIBS ${VORBIS_LIBRARY})
	list(APPEND ${DepName}_LIBS ${VORBIS_LIBRARY2})
ELSE()
    SET(${DepName}_INCLUDE_DIR "")
	list(APPEND ${DepName}_LIBS "vorbisfile")
    list(APPEND ${DepName}_LIBS "vorbis")
 	list(APPEND ${DepName}_LIBS "m")
ENDIF()

