SET(DepName "gclreaderwriterqueue")

SET(READERWRITERQUEUE_ROOT "${CMAKE_CURRENT_LIST_DIR}/../binaries/${CMAKE_SYSTEM_NAME}${CMAKE_CXX_COMPILER_ID}${KINEVOX_ARCHITECTURE}/usr/")

FIND_PATH(
		  READERWRITERQUEUE_INCLUDE_DIR readerwriterqueue.h
		  PATHS ${READERWRITERQUEUE_ROOT}/include/readerwriterqueue
		  NO_DEFAULT_PATH)
		
SET(${DepName}_INCLUDE_DIR  ${READERWRITERQUEUE_INCLUDE_DIR})
list(APPEND ${DepName}_LIBS "")

