SET(DepName "gclreaderwriterqueue")

SET(READERWRITERQUEUE_ROOT "${CMAKE_CURRENT_LIST_DIR}/../binaries/${CMAKE_SYSTEM_NAME}${CMAKE_CXX_COMPILER_ID}${KINEVOX_ARCHITECTURE}/usr/")

SET(${DepName}_INCLUDE_DIR  ${READERWRITERQUEUE_ROOT}/include/readerwriterqueue)
list(APPEND ${DepName}_LIBS "")

