SET(DepName "gclvorbis")

SET(VORBIS_ROOT "${CMAKE_CURRENT_LIST_DIR}/../binaries/${CMAKE_SYSTEM_NAME}${CMAKE_CXX_COMPILER_ID}${KINEVOX_ARCHITECTURE}/usr/local/")
SET(LPATH ${VORBIS_ROOT}/lib/)
SET(LIB_NAME "libvorbis")
SET(LIB_NAME2 "libvorbisfile")

SET(VORBIS_INCLUDE_DIR ${VORBIS_ROOT}/include)
FindLibrary(VORBIS_LIBRARY ${LIB_NAME} ${LPATH})
FindLibrary(VORBIS_LIBRARY2 ${LIB_NAME2} ${LPATH})
	  
SET(${DepName}_INCLUDE_DIR ${VORBIS_INCLUDE_DIR} )
list(APPEND ${DepName}_LIBS ${VORBIS_LIBRARY})
list(APPEND ${DepName}_LIBS ${VORBIS_LIBRARY2})
if (NOT ${MSVC})
 	list(APPEND ${DepName}_LIBS "m")
ENDIF()

