SET(DepName "gclzlib")

SET(ZLIB_ROOT "${CMAKE_CURRENT_LIST_DIR}/../binaries/${CMAKE_SYSTEM_NAME}${CMAKE_CXX_COMPILER_ID}${KINEVOX_ARCHITECTURE}/usr/local/")
SET(LPATH ${ZLIB_ROOT}/lib/)
if(${WIN32})
    SET(LIB_NAME "zlibstatic")
ELSE()
    SET(LIB_NAME "libz")
ENDIF()
FIND_PATH(
		  ZLIB_INCLUDE_DIR zlib.h
		  PATHS ${ZLIB_ROOT}/include)
		
FindLibrary(ZLIB_LIBRARY ${LIB_NAME} ${LPATH})
SET(${DepName}_INCLUDE_DIR  ${ZLIB_INCLUDE_DIR})
list(APPEND ${DepName}_LIBS ${ZLIB_LIBRARY})

